version: "3.8"
services:
  database:
    image: postgres:16
    container_name: database
    env_file:
      - .env-prod

  meili:
    image: getmeili/meilisearch:v1.7
    container_name: meili
    ports:
      - 7700:7700

  app:
    build:
      context: .
    container_name: backend
    command: alembic upgrade head; cd src; gunicorn main:app --workers 3 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000
    volumes:
      - ./:/app
      - /app/.venv
    env_file:
      - .env-prod
    ports:
      - 1234:8000
    depends_on:
      - database
      - meili
