version: "3.9"
services:
  database:
    image: postgres:16
    container_name: database
    env_file:
      - .env-prod

  meili:
    image: getmeili/meilisearch:v1.7
    container_name: meili
    volumes:
      - ./data.ms:/data.ms
    env_file:
      - .env-prod
    ports:
      - 7700:7700

  backend:
    build:
      context: .
    container_name: backend
    volumes:
      - ./docker/:/backend/docker
    env_file:
      - .env-prod
    command: /docker/backend.sh
    ports:
      - 1234:8000
    depends_on:
      - database
      - meili
