"""06_05_1

Revision ID: 40a43d5c5a1e
Revises: 91ae177cc901
Create Date: 2024-05-06 16:09:42.111612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a43d5c5a1e'
down_revision: Union[str, None] = '91ae177cc901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('file_name', sa.String(length=128), nullable=True))
    op.add_column('media_files', sa.Column('file_url', sa.String(length=128), nullable=True))
    op.alter_column('media_files', 'data',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('media_files', 'name')
    op.drop_column('media_files', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_files', sa.Column('url', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('media_files', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.alter_column('media_files', 'data',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('media_files', 'file_url')
    op.drop_column('media_files', 'file_name')
    # ### end Alembic commands ###
