"""28_2

Revision ID: c29648c37955
Revises: 4bb932abf08b
Create Date: 2024-04-28 14:54:27.520586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c29648c37955'
down_revision: Union[str, None] = '4bb932abf08b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategories', sa.Column('category_id', sa.Integer(), nullable=False))
    op.drop_constraint('subcategories_section_id_fkey', 'subcategories', type_='foreignkey')
    op.create_foreign_key(None, 'subcategories', 'categories', ['category_id'], ['id'])
    op.drop_column('subcategories', 'section_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategories', sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.create_foreign_key('subcategories_section_id_fkey', 'subcategories', 'categories', ['section_id'], ['id'])
    op.drop_column('subcategories', 'category_id')
    # ### end Alembic commands ###
