"""14.05_1

Revision ID: e5f26e80bf65
Revises: d2ce6b393efb
Create Date: 2024-05-14 21:45:48.758258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f26e80bf65'
down_revision: Union[str, None] = 'd2ce6b393efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_subcategory_id_fkey', 'posts', type_='foreignkey')
    op.drop_constraint('posts_category_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'subcategories', ['subcategory_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'posts', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_category_id_fkey', 'posts', 'categories', ['category_id'], ['id'])
    op.create_foreign_key('posts_subcategory_id_fkey', 'posts', 'subcategories', ['subcategory_id'], ['id'])
    # ### end Alembic commands ###
