"""21.05_1

Revision ID: f6c1a70acd25
Revises: e5f26e80bf65
Create Date: 2024-05-21 23:04:51.294782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c1a70acd25'
down_revision: Union[str, None] = 'e5f26e80bf65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_information', sa.Column('post_id', sa.Integer(), nullable=False))
    op.drop_constraint('personal_information_informational_content_id_fkey', 'personal_information', type_='foreignkey')
    op.create_foreign_key(None, 'personal_information', 'posts', ['post_id'], ['id'])
    op.drop_column('personal_information', 'informational_content_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_information', sa.Column('informational_content_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'personal_information', type_='foreignkey')
    op.create_foreign_key('personal_information_informational_content_id_fkey', 'personal_information', 'posts', ['informational_content_id'], ['id'])
    op.drop_column('personal_information', 'post_id')
    # ### end Alembic commands ###
